{"code":"23505","constraint":"REL_373ead146f110f04dad6084815","detail":"Key (\"userId\")=(1) already exists.","driverError":{"code":"23505","constraint":"REL_373ead146f110f04dad6084815","detail":"Key (\"userId\")=(1) already exists.","file":"nbtinsert.c","length":225,"line":"666","name":"error","routine":"_bt_check_unique","schema":"public","severity":"ERROR","table":"auth"},"file":"nbtinsert.c","length":225,"level":"error","line":"666","message":"Error signing up user: duplicate key value violates unique constraint \"REL_373ead146f110f04dad6084815\"","parameters":["8cc8198b-c871-43bf-a4c4-4b467200e8c0:fed4e04ec652e8cee47ebdccbd6cac23d79d0613aa2fbf308e37ae283da47e92",1],"query":"INSERT INTO \"auth\"(\"password\", \"createdAt\", \"updatedAt\", \"userId\") VALUES ($1, DEFAULT, DEFAULT, $2) RETURNING \"id\", \"createdAt\", \"updatedAt\"","routine":"_bt_check_unique","schema":"public","severity":"ERROR","stack":"QueryFailedError: duplicate key value violates unique constraint \"REL_373ead146f110f04dad6084815\"\n    at PostgresQueryRunner.query (/media/joaquin/Joaquin/Proyectos/conexa-challenge/node_modules/typeorm/driver/src/driver/postgres/PostgresQueryRunner.ts:325:19)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at InsertQueryBuilder.execute (/media/joaquin/Joaquin/Proyectos/conexa-challenge/node_modules/typeorm/query-builder/src/query-builder/InsertQueryBuilder.ts:163:33)\n    at SubjectExecutor.executeInsertOperations (/media/joaquin/Joaquin/Proyectos/conexa-challenge/node_modules/typeorm/persistence/src/persistence/SubjectExecutor.ts:435:42)\n    at SubjectExecutor.execute (/media/joaquin/Joaquin/Proyectos/conexa-challenge/node_modules/typeorm/persistence/src/persistence/SubjectExecutor.ts:137:9)\n    at EntityPersistExecutor.execute (/media/joaquin/Joaquin/Proyectos/conexa-challenge/node_modules/typeorm/persistence/src/persistence/EntityPersistExecutor.ts:182:21)\n    at AuthService.signup (/media/joaquin/Joaquin/Proyectos/conexa-challenge/src/components/auth/auth.service.ts:76:25)\n    at AuthController.signup (/media/joaquin/Joaquin/Proyectos/conexa-challenge/src/components/auth/auth.controller.ts:27:20)","table":"auth","timestamp":"2025-06-01 00:41:46"}
{"level":"error","message":"Error signing up user","name":"InternalServerErrorException","options":{},"response":{"error":"Internal Server Error","message":"Error signing up user","statusCode":500},"stack":"InternalServerErrorException: Error signing up user\n    at AuthService.signup (/media/joaquin/Joaquin/Proyectos/conexa-challenge/src/components/auth/auth.service.ts:87:13)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at AuthController.signup (/media/joaquin/Joaquin/Proyectos/conexa-challenge/src/components/auth/auth.controller.ts:27:20)","status":500,"timestamp":"2025-06-01 00:41:46"}
{"code":"23505","constraint":"REL_373ead146f110f04dad6084815","detail":"Key (\"userId\")=(2) already exists.","driverError":{"code":"23505","constraint":"REL_373ead146f110f04dad6084815","detail":"Key (\"userId\")=(2) already exists.","file":"nbtinsert.c","length":225,"line":"666","name":"error","routine":"_bt_check_unique","schema":"public","severity":"ERROR","table":"auth"},"file":"nbtinsert.c","length":225,"level":"error","line":"666","message":"Error signing up user: duplicate key value violates unique constraint \"REL_373ead146f110f04dad6084815\"","parameters":["253cb1cc-297c-40bc-9c63-dfee642af161:47716d9a308f2405cb46f7955decb7e3f25c96d946c5791c001fb1361a350b66",2],"query":"INSERT INTO \"auth\"(\"password\", \"createdAt\", \"updatedAt\", \"userId\") VALUES ($1, DEFAULT, DEFAULT, $2) RETURNING \"id\", \"createdAt\", \"updatedAt\"","routine":"_bt_check_unique","schema":"public","severity":"ERROR","stack":"QueryFailedError: duplicate key value violates unique constraint \"REL_373ead146f110f04dad6084815\"\n    at PostgresQueryRunner.query (/media/joaquin/Joaquin/Proyectos/conexa-challenge/node_modules/typeorm/driver/src/driver/postgres/PostgresQueryRunner.ts:325:19)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at InsertQueryBuilder.execute (/media/joaquin/Joaquin/Proyectos/conexa-challenge/node_modules/typeorm/query-builder/src/query-builder/InsertQueryBuilder.ts:163:33)\n    at SubjectExecutor.executeInsertOperations (/media/joaquin/Joaquin/Proyectos/conexa-challenge/node_modules/typeorm/persistence/src/persistence/SubjectExecutor.ts:435:42)\n    at SubjectExecutor.execute (/media/joaquin/Joaquin/Proyectos/conexa-challenge/node_modules/typeorm/persistence/src/persistence/SubjectExecutor.ts:137:9)\n    at EntityPersistExecutor.execute (/media/joaquin/Joaquin/Proyectos/conexa-challenge/node_modules/typeorm/persistence/src/persistence/EntityPersistExecutor.ts:182:21)\n    at AuthService.signup (/media/joaquin/Joaquin/Proyectos/conexa-challenge/src/components/auth/auth.service.ts:76:25)\n    at AuthController.signup (/media/joaquin/Joaquin/Proyectos/conexa-challenge/src/components/auth/auth.controller.ts:27:20)","table":"auth","timestamp":"2025-06-01 00:46:25"}
{"level":"error","message":"Error signing up user","name":"InternalServerErrorException","options":{},"response":{"error":"Internal Server Error","message":"Error signing up user","statusCode":500},"stack":"InternalServerErrorException: Error signing up user\n    at AuthService.signup (/media/joaquin/Joaquin/Proyectos/conexa-challenge/src/components/auth/auth.service.ts:87:13)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at AuthController.signup (/media/joaquin/Joaquin/Proyectos/conexa-challenge/src/components/auth/auth.controller.ts:27:20)","status":500,"timestamp":"2025-06-01 00:46:25"}
